// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Entrada
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public DateTime FechaRegistro { get; set; }

    public int Conteo { get; set; }
}