// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Entradas_Salidas.Models;

public partial class ENTRADAS_SALIDASContext : DbContext
{
    public ENTRADAS_SALIDASContext()
    {
    }

    public ENTRADAS_SALIDASContext(DbContextOptions<ENTRADAS_SALIDASContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Entrada> Entradas { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
      
    => optionsBuilder.UseSqlServer("Data Source=DESKTOP-5P8JJPQ;Initial Catalog=ENTRADAS_SALIDAS;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Entrada>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__ENTRADAS__3214EC07A59E582D");

            entity.ToTable("ENTRADAS");

            entity.Property(e => e.Codigo).IsUnicode(false);
            entity.Property(e => e.FechaRegistro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}