// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Historialinventario
{
    public int Id { get; set; }

    public string Codigo { get; set; }

    public int CantidadEntrada { get; set; }

    public int CantidadSalida { get; set; }

    public int CantidadFinal { get; set; }

    public DateTime FechaEntrada { get; set; }

    public DateTime? FechaSalida { get; set; }
}