// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class PlannerArchivo
{
    public int Id { get; set; }

    public decimal? OrdenProduccion { get; set; }

    public string NumeroParte { get; set; }

    public DateTime? FechaProduccionCarrier { get; set; }

    public byte? Cantidad { get; set; }
}