// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StockControl.Models;

public partial class Planner
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    [Range(1,int.MaxValue, ErrorMessage = "Maximo 9 digitos")]
    public int? ShopOrder { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    public string Codigo { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    public DateTime? Fecha { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    public string Cantidad { get; set; }

    public string Codigo2 { get; set; }

    public string Codigo3 { get; set; }

    public string Codigo4 { get; set; }

    public string Codigo5 { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    public int? Cantidad2 { get; set; }

    public int? Cantidad3 { get; set; }

    public int? Cantidad4 { get; set; }

    public int? Cantidad5 { get; set; }

    public int? Cantidad6 { get; set; }

    public string Codigo6 { get; set; }

    public int? Cantidad7 { get; set; }
}