// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace StockControl.Models;

public partial class Register
{
    public int Id { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    [RegularExpression("^[a-zA-Z0-9_\\.-]+@([a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,6}$", ErrorMessage = "Debes ingresar un email valido")]
    public string Email { get; set; }

    [Required(ErrorMessage = "Este campo es requerido")]
    public string Password { get; set; }

    public int? FkRol { get; set; }

    public virtual Rol FkRolNavigation { get; set; }
}