// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Registrohistorico
{
    public int Id { get; set; }

    public string PartNumber { get; set; }

    public int? TotalQunatity { get; set; }

    public DateTime? Fecha { get; set; }

    public bool OrderFulfilled { get; set; }

    public int? ShopOrderId { get; set; }
}