// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Register
{
    public int Id { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public int? FkRol { get; set; }

    public virtual Rol FkRolNavigation { get; set; }
}