// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Rol
{
    public int Id { get; set; }

    public string Rol1 { get; set; }

    public virtual ICollection<Register> Registers { get; set; } = new List<Register>();
}