// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace StockControl.Models;

public partial class Shoporder
{
    public int Id { get; set; }

    public int? ShopOrder1 { get; set; }

    public string Codigo { get; set; }

    public int? CantidadTotal { get; set; }

    public DateTime? FechaShopOrder { get; set; }
}